### ISSUE TITLE
Missing ROR logo on Search page in some browsers

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#31]
@cazinc I just noticed that the ROR logo has gone missing on the Search page in certain browsers. I am able to see it in Firefox but not in Chrome or Safari, and my colleagues have confirmed this as well. Are you able to diagnose what might have happened?

CC @mfenner @eshadatta-crossref 
![Screen Shot 2020-04-15 at 5 05 08 PM](https://user-images.githubusercontent.com/45110557/79400459-2643d880-7f3b-11ea-95ba-9c67842df078.png)
![Screen Shot 2020-04-15 at 5 05 29 PM](https://user-images.githubusercontent.com/45110557/79400463-27750580-7f3b-11ea-9c6b-7bb09fc8be28.png)

**Comment by cazinc** [comment]
Hi @mariagould this should be fixed how. Was down to an issue that only affected Firefox (seemed to be fine on Chrome and Safari in our testing). You can review on dev.ror.org. 

The problem actually existed on both the site and the search pages, but should be working on both now. Don't forget to refresh the page if you can't see it. 

I think if this is the last thing, there are quite a few fixes that need to go up onto the live ROR site now, is that true? Would you like us to sort that?

**Comment by mariagould** [comment]
Thank you @cazinc this looks good to me on dev. 

I think we may be caught up on the style updates for now. I will pull dev into staging and then merge to master. Will let you know if any weirdness remains! Thanks again for all your help.

**Comment by cazinc** [comment]
Great, sounds good Maria.

There will be at least one issue that needs resolution after you merge, just because the search functionality references the dev site in a couple hard-coded places. It won’t cause any visible issues, so just let me know once you’ve merged and I will come back through and fix - should hopefully just take a couple minutes.


Zach Anthony
Managing Director, Cazinc (Ltd) Digital
Digital consultancy & web development
Tel +44 (0)131 202 6499 | Mob +44 (0)7810 403 497 | Email zach@cazinc.co.uk | Web cazinc.co.uk
Registered in Scotland No. SC287248. VAT Registration No. GB973077006 Cazinc has its registered office at 13/1 Spottiswoode Road, Edinburgh, EH9 1BH. This email and its attachments are confidential and may contain information intended only for the recipient/s named above. Any views or opinions expressed within the email are solely those of its author and do not necessarily represent those of Cazinc Ltd. If you not an intended recipient you are informed that any copying, distribution, disclosure, reliance upon or other use of the contents of this email is strictly prohibited. If you believe you have received this email in error please notify the sender immediately and destroy it.

**Comment by mariagould** [comment]
Merged to master - and sent you a Slack message about some weirdness I am seeing!
