### ISSUE TITLE
Add sub-pages to main navigation

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#49]
The current main nav of the ROR website only supports linking to an individual page from each nav item. We want to build sub-navigation into the main navigation menu so that users can access sub-pages that might otherwise be hidden or hard to find. This update will support the nav updates described in #48.

**Comment by cazinc** [comment]
Hi @mariagould just to clarify, are you looking for dropdown here? These can be an accessibility & UX issue. Do you have something specific in mind?

**Comment by mariagould** [comment]
Hi @cazinc yes, a dropdown that appears upon hover or click so users can see a list of pages - something like the below image. 
![Screen Shot 2022-07-20 at 7 43 28 AM](https://user-images.githubusercontent.com/45110557/180011444-c5181232-b6db-48ba-b7c0-980f4667c1cf.png)

**Comment by cazinc** [comment]
Are you open to other suggestions @mariagould? The example provided is the sort of dropdown that presents accessibility & UX issues unfortunately, and I know from other Issues here that you are looking to improve on this. 

In no particular order, options include:

1. The "mega menu" style of nav you see on the [Crossref site](https://www.crossref.org/);
2. A smaller mega menu more akin to traditional dropdown, that only shows "near" the nav bar itself instead of replacing the whole page ([here's an example](https://www.morton-fraser.com));
3. Going without dropdown nav but instead utilising clear subnav within sections, more blocks on homepage that direct users to deeper pages, etc. Basically this solution is about creating new user journeys rather than relying on dropdown. You've already spec'd the changes necessary to support this route (#55 & #50). 

I usually recommend to go at this sort of thing one step at a time, which in this case could mean completing #55 and #50 and seeing what you think as a first step. 

What's your preference?

**Comment by mariagould** [comment]
Hi @cazinc definitely open to and eager for your suggestions; thank you for weighing in! Let's start with #55 and #50 for now and then determine next steps after that.

**Comment by cazinc** [comment]
Great @mariagould will do.

**Comment by cazinc** [comment]
Just moved this into a new Blocked column pending later review @mariagould, FYI
