### ISSUE TITLE
Update footer design/links

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#58]
ROR website users should be able to quickly access information about ROR from the footer menu. 

To do:

**1. Add a row of social/follow icons**

Add a light-gray block to the footer above the dark-gray one and include the following linked icons, aligned in the center of the block:

Email (linked to mailto:info@ror.org)
Twitter (linked to https://twitter.com/ResearchOrgs)
YouTube (linked to https://www.youtube.com/channel/UCQBOpOpW-JEKoVCUlmCK1Eg)
LinkedIn (linked to https://www.linkedin.com/company/ror-research-organization-registry/)
Github (linked to https://github.com/ror-community)
Support site (linked to https://ror.readme.io)

![Screen Shot 2022-07-14 at 8 04 09 AM](https://user-images.githubusercontent.com/45110557/179014359-69293501-182c-4e06-9822-bd4ab42c5b63.png)

**2. Add a button to submit registry feedback in the same block as the mailing list signup.** 

General mockup:

<img width="709" alt="Screen Shot 2022-07-18 at 11 28 36 AM" src="https://user-images.githubusercontent.com/45110557/179578802-844559d7-908c-4d14-80fb-89601feb5fad.png">

Icons in the mockup are from iconmonstr but other sources are also fine.

**Comment by cazinc** [comment]
@mariagould would you like us to retain, or remove, the Twitter link up in the main nav? I'm thinking remove since it will now be in this new area of the footer, and also so as not to give it precedence over the other platforms (unless that is actually a goal!).

**Comment by mariagould** [comment]
Hi @cazinc yes, let's remove the Twitter icon from the main nav.

**Comment by cazinc** [comment]
Great, thanks for confirming @mariagould

**Comment by cazinc** [comment]
This is all in place in the the Summer-2022-updates branch @mariagould.

We've made the round button style consistent now (subscribe form used to be square), and retained the red in this block. We also made the new **Submit a curation request** button right aligned rather than centred as we thought it might look better in terms of balancing the left-aligned **Subscribe** button, but this is easily changed - just let me know your pref. 

On the new Socials bar, the "slots" are hard-coded (1 for each of the 6 icons) as are the icons themselves, but you can manage the URLs for each in the .toml file (currently just localhost.toml). This could all be made more flexible if you think it will change often, or if you look at `../themes/hugo-ror/layouts/partials/socials.html` it should be relatively clear how to make changes to one of the slots. Happy to go through it too if ever needed. 

Let me know what you think.

**Comment by cazinc** [comment]
Thanks for pointing out that issue with all of the social icons having a mailto: in the URL @mariagould - now fixed, and I've just merged into the dev branch too.

**Comment by mariagould** [comment]
Documenting additional feedback/discussion from earlier today: 

- Update the curation request section in the footer to minimize redundancy: Change the text preceding the button to "Have a suggestion for an addition or update to ROR?

**Comment by cazinc** [comment]
This change has now been made @mariagould

**Comment by mariagould** [comment]
Looks good @cazinc !
